services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:release
    networks:
      - reinhardt_net
    volumes:
      - ${LIBRARY_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=immich.reinhardt.ai
      - LETSENCRYPT_HOST=immich.reinhardt.ai
      - VIRTUAL_PORT=2283
      - LIBHEIF_SECURITY_LIMITS=OFF
    depends_on:
      - redis
      - database
    restart: always
    logging:
      options:
        max-size: "50m"

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - REDIS_HOSTNAME=redis
    restart: on-failure:10
    networks:
      - reinhardt_net
    logging:
      options:
        max-size: "50m"

  redis:
    container_name: immich-redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:facc1d2c3462975c34e10fccb167bfa92b0e0dbd992fc282c29a61c3243afb11
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - reinhardt_net
    restart: on-failure:10
    logging:
      options:
        max-size: "50m"

  database:
    container_name: immich-database
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:32324a2f41df5de9efe1af166b7008c3f55646f8d0e00d9550c16c9822366b4a
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_INITDB_ARGS="--data-checksums"
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: on-failure:10
    networks:
      - reinhardt_net
    logging:
      options:
        max-size: "50m"

networks:
  reinhardt_net:
    external: true
  immich_backup_net:
    driver: bridge

volumes:
  model-cache:
